package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name="account_type"
    ,catalog="university"
    , uniqueConstraints = @UniqueConstraint(columnNames="acc_type_name") 
)
public class AccountType  implements java.io.Serializable {


     private Integer accTypeId;
     private String accTypeName;
     private Set<Login> logins = new HashSet<Login>(0);

    public AccountType() {
    }

	
    public AccountType(String accTypeName) {
        this.accTypeName = accTypeName;
    }
    public AccountType(String accTypeName, Set<Login> logins) {
       this.accTypeName = accTypeName;
       this.logins = logins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="acc_type_id", unique=true, nullable=false)
    public Integer getAccTypeId() {
        return this.accTypeId;
    }
    
    public void setAccTypeId(Integer accTypeId) {
        this.accTypeId = accTypeId;
    }

    
    @Column(name="acc_type_name", unique=true, nullable=false, length=45)
    public String getAccTypeName() {
        return this.accTypeName;
    }
    
    public void setAccTypeName(String accTypeName) {
        this.accTypeName = accTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountType")
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }




}


