package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AttendenceValue generated by hbm2java
 */
@Entity
@Table(name="attendence_value"
    ,catalog="university"
)
public class AttendenceValue  implements java.io.Serializable {


     private Integer attValId;
     private String attValName;
     private Set<Attendence> attendences = new HashSet<Attendence>(0);

    public AttendenceValue() {
    }

	
    public AttendenceValue(String attValName) {
        this.attValName = attValName;
    }
    public AttendenceValue(String attValName, Set<Attendence> attendences) {
       this.attValName = attValName;
       this.attendences = attendences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="att_val_id", unique=true, nullable=false)
    public Integer getAttValId() {
        return this.attValId;
    }
    
    public void setAttValId(Integer attValId) {
        this.attValId = attValId;
    }

    
    @Column(name="att_val_name", nullable=false, length=45)
    public String getAttValName() {
        return this.attValName;
    }
    
    public void setAttValName(String attValName) {
        this.attValName = attValName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="attendenceValue")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set<Attendence> attendences) {
        this.attendences = attendences;
    }




}


