package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendence generated by hbm2java
 */
@Entity
@Table(name="attendence"
    ,catalog="university"
)
public class Attendence  implements java.io.Serializable {


     private Integer attendId;
     private AttendenceValue attendenceValue;
     private ClassHour classHour;
     private StudentInfo studentInfo;
     private Subject subject;
     private Teachers teachers;
     private Date attendDate;

    public Attendence() {
    }

    public Attendence(AttendenceValue attendenceValue, ClassHour classHour, StudentInfo studentInfo, Subject subject, Teachers teachers, Date attendDate) {
       this.attendenceValue = attendenceValue;
       this.classHour = classHour;
       this.studentInfo = studentInfo;
       this.subject = subject;
       this.teachers = teachers;
       this.attendDate = attendDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="attend_id", unique=true, nullable=false)
    public Integer getAttendId() {
        return this.attendId;
    }
    
    public void setAttendId(Integer attendId) {
        this.attendId = attendId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="att_val_id", nullable=false)
    public AttendenceValue getAttendenceValue() {
        return this.attendenceValue;
    }
    
    public void setAttendenceValue(AttendenceValue attendenceValue) {
        this.attendenceValue = attendenceValue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hour_id", nullable=false)
    public ClassHour getClassHour() {
        return this.classHour;
    }
    
    public void setClassHour(ClassHour classHour) {
        this.classHour = classHour;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id", nullable=false)
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="attend_date", nullable=false, length=10)
    public Date getAttendDate() {
        return this.attendDate;
    }
    
    public void setAttendDate(Date attendDate) {
        this.attendDate = attendDate;
    }




}


