package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassHour generated by hbm2java
 */
@Entity
@Table(name="class_hour"
    ,catalog="university"
)
public class ClassHour  implements java.io.Serializable {


     private Integer hourId;
     private String hourName;
     private Set<Attendence> attendences = new HashSet<Attendence>(0);
     private Set<Routine> routines = new HashSet<Routine>(0);

    public ClassHour() {
    }

	
    public ClassHour(String hourName) {
        this.hourName = hourName;
    }
    public ClassHour(String hourName, Set<Attendence> attendences, Set<Routine> routines) {
       this.hourName = hourName;
       this.attendences = attendences;
       this.routines = routines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="hour_id", unique=true, nullable=false)
    public Integer getHourId() {
        return this.hourId;
    }
    
    public void setHourId(Integer hourId) {
        this.hourId = hourId;
    }

    
    @Column(name="hour_name", nullable=false, length=45)
    public String getHourName() {
        return this.hourName;
    }
    
    public void setHourName(String hourName) {
        this.hourName = hourName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classHour")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set<Attendence> attendences) {
        this.attendences = attendences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classHour")
    public Set<Routine> getRoutines() {
        return this.routines;
    }
    
    public void setRoutines(Set<Routine> routines) {
        this.routines = routines;
    }




}


