package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassDay generated by hbm2java
 */
@Entity
@Table(name="class_day"
    ,catalog="university"
)
public class ClassDay  implements java.io.Serializable {


     private Integer dayId;
     private String dayName;
     private Set<Routine> routines = new HashSet<Routine>(0);

    public ClassDay() {
    }

	
    public ClassDay(String dayName) {
        this.dayName = dayName;
    }
    public ClassDay(String dayName, Set<Routine> routines) {
       this.dayName = dayName;
       this.routines = routines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="day_id", unique=true, nullable=false)
    public Integer getDayId() {
        return this.dayId;
    }
    
    public void setDayId(Integer dayId) {
        this.dayId = dayId;
    }

    
    @Column(name="day_name", nullable=false, length=45)
    public String getDayName() {
        return this.dayName;
    }
    
    public void setDayName(String dayName) {
        this.dayName = dayName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classDay")
    public Set<Routine> getRoutines() {
        return this.routines;
    }
    
    public void setRoutines(Set<Routine> routines) {
        this.routines = routines;
    }




}


