package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name="designation"
    ,catalog="university"
    , uniqueConstraints = @UniqueConstraint(columnNames="desig_name") 
)
public class Designation  implements java.io.Serializable {


     private Integer desigId;
     private String desigName;
     private Set<EmpInfo> empInfos = new HashSet<EmpInfo>(0);

    public Designation() {
    }

	
    public Designation(String desigName) {
        this.desigName = desigName;
    }
    public Designation(String desigName, Set<EmpInfo> empInfos) {
       this.desigName = desigName;
       this.empInfos = empInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="desig_id", unique=true, nullable=false)
    public Integer getDesigId() {
        return this.desigId;
    }
    
    public void setDesigId(Integer desigId) {
        this.desigId = desigId;
    }

    
    @Column(name="desig_name", unique=true, nullable=false, length=45)
    public String getDesigName() {
        return this.desigName;
    }
    
    public void setDesigName(String desigName) {
        this.desigName = desigName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="designation")
    public Set<EmpInfo> getEmpInfos() {
        return this.empInfos;
    }
    
    public void setEmpInfos(Set<EmpInfo> empInfos) {
        this.empInfos = empInfos;
    }




}


