package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpInfo generated by hbm2java
 */
@Entity
@Table(name="emp_info"
    ,catalog="university"
)
public class EmpInfo  implements java.io.Serializable {


     private Integer empId;
     private Designation designation;
     private String empName;
     private String empFather;
     private String empMother;
     private String empAddress;
     private Date empDob;
     private String empMobile;
     private String empPic;
     private Date joinDate;
     private Set<Teachers> teacherses = new HashSet<Teachers>(0);
     private Set<SalaryInfo> salaryInfos = new HashSet<SalaryInfo>(0);

    public EmpInfo() {
    }

	
    public EmpInfo(Designation designation, String empName, String empFather, String empMother, String empAddress, Date empDob, String empMobile, String empPic, Date joinDate) {
        this.designation = designation;
        this.empName = empName;
        this.empFather = empFather;
        this.empMother = empMother;
        this.empAddress = empAddress;
        this.empDob = empDob;
        this.empMobile = empMobile;
        this.empPic = empPic;
        this.joinDate = joinDate;
    }
    public EmpInfo(Designation designation, String empName, String empFather, String empMother, String empAddress, Date empDob, String empMobile, String empPic, Date joinDate, Set<Teachers> teacherses, Set<SalaryInfo> salaryInfos) {
       this.designation = designation;
       this.empName = empName;
       this.empFather = empFather;
       this.empMother = empMother;
       this.empAddress = empAddress;
       this.empDob = empDob;
       this.empMobile = empMobile;
       this.empPic = empPic;
       this.joinDate = joinDate;
       this.teacherses = teacherses;
       this.salaryInfos = salaryInfos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emp_id", unique=true, nullable=false)
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="desig_id", nullable=false)
    public Designation getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(Designation designation) {
        this.designation = designation;
    }

    
    @Column(name="emp_name", nullable=false, length=45)
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    
    @Column(name="emp_father", nullable=false, length=45)
    public String getEmpFather() {
        return this.empFather;
    }
    
    public void setEmpFather(String empFather) {
        this.empFather = empFather;
    }

    
    @Column(name="emp_mother", nullable=false, length=45)
    public String getEmpMother() {
        return this.empMother;
    }
    
    public void setEmpMother(String empMother) {
        this.empMother = empMother;
    }

    
    @Column(name="emp_address", nullable=false, length=45)
    public String getEmpAddress() {
        return this.empAddress;
    }
    
    public void setEmpAddress(String empAddress) {
        this.empAddress = empAddress;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="emp_dob", nullable=false, length=10)
    public Date getEmpDob() {
        return this.empDob;
    }
    
    public void setEmpDob(Date empDob) {
        this.empDob = empDob;
    }

    
    @Column(name="emp_mobile", nullable=false, length=45)
    public String getEmpMobile() {
        return this.empMobile;
    }
    
    public void setEmpMobile(String empMobile) {
        this.empMobile = empMobile;
    }

    
    @Column(name="emp_pic", nullable=false, length=5000)
    public String getEmpPic() {
        return this.empPic;
    }
    
    public void setEmpPic(String empPic) {
        this.empPic = empPic;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="join_date", nullable=false, length=10)
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empInfo")
    public Set<Teachers> getTeacherses() {
        return this.teacherses;
    }
    
    public void setTeacherses(Set<Teachers> teacherses) {
        this.teacherses = teacherses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empInfo")
    public Set<SalaryInfo> getSalaryInfos() {
        return this.salaryInfos;
    }
    
    public void setSalaryInfos(Set<SalaryInfo> salaryInfos) {
        this.salaryInfos = salaryInfos;
    }




}


