package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Exam generated by hbm2java
 */
@Entity
@Table(name="exam"
    ,catalog="university"
)
public class Exam  implements java.io.Serializable {


     private Integer examId;
     private Department department;
     private Program program;
     private Semister semister;
     private String examName;
     private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(0);

    public Exam() {
    }

	
    public Exam(Department department, Program program, Semister semister, String examName) {
        this.department = department;
        this.program = program;
        this.semister = semister;
        this.examName = examName;
    }
    public Exam(Department department, Program program, Semister semister, String examName, Set<ExamSchedule> examSchedules) {
       this.department = department;
       this.program = program;
       this.semister = semister;
       this.examName = examName;
       this.examSchedules = examSchedules;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="exam_id", unique=true, nullable=false)
    public Integer getExamId() {
        return this.examId;
    }
    
    public void setExamId(Integer examId) {
        this.examId = examId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sem_id", nullable=false)
    public Semister getSemister() {
        return this.semister;
    }
    
    public void setSemister(Semister semister) {
        this.semister = semister;
    }

    
    @Column(name="exam_name", nullable=false, length=45)
    public String getExamName() {
        return this.examName;
    }
    
    public void setExamName(String examName) {
        this.examName = examName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="exam")
    public Set<ExamSchedule> getExamSchedules() {
        return this.examSchedules;
    }
    
    public void setExamSchedules(Set<ExamSchedule> examSchedules) {
        this.examSchedules = examSchedules;
    }




}


