package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExamSchedule generated by hbm2java
 */
@Entity
@Table(name="exam_schedule"
    ,catalog="university"
)
public class ExamSchedule  implements java.io.Serializable {


     private Integer scheduleId;
     private Exam exam;
     private Subject subject;
     private Date examDate;

    public ExamSchedule() {
    }

    public ExamSchedule(Exam exam, Subject subject, Date examDate) {
       this.exam = exam;
       this.subject = subject;
       this.examDate = examDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="schedule_id", unique=true, nullable=false)
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam_id", nullable=false)
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="exam_date", nullable=false, length=10)
    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }




}


