package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Faculty generated by hbm2java
 */
@Entity
@Table(name="faculty"
    ,catalog="university"
)
public class Faculty  implements java.io.Serializable {


     private Integer facId;
     private String facName;
     private String facTitle;
     private String facSubTitle;
     private String facDesc;
     private Set<Department> departments = new HashSet<Department>(0);

    public Faculty() {
    }

	
    public Faculty(String facName) {
        this.facName = facName;
    }
    public Faculty(String facName, String facTitle, String facSubTitle, String facDesc, Set<Department> departments) {
       this.facName = facName;
       this.facTitle = facTitle;
       this.facSubTitle = facSubTitle;
       this.facDesc = facDesc;
       this.departments = departments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="fac_id", unique=true, nullable=false)
    public Integer getFacId() {
        return this.facId;
    }
    
    public void setFacId(Integer facId) {
        this.facId = facId;
    }

    
    @Column(name="fac_name", nullable=false, length=45)
    public String getFacName() {
        return this.facName;
    }
    
    public void setFacName(String facName) {
        this.facName = facName;
    }

    
    @Column(name="fac_title", length=300)
    public String getFacTitle() {
        return this.facTitle;
    }
    
    public void setFacTitle(String facTitle) {
        this.facTitle = facTitle;
    }

    
    @Column(name="fac_sub_title", length=300)
    public String getFacSubTitle() {
        return this.facSubTitle;
    }
    
    public void setFacSubTitle(String facSubTitle) {
        this.facSubTitle = facSubTitle;
    }

    
    @Column(name="fac_desc", length=5000)
    public String getFacDesc() {
        return this.facDesc;
    }
    
    public void setFacDesc(String facDesc) {
        this.facDesc = facDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }




}


