package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name="grade"
    ,catalog="university"
)
public class Grade  implements java.io.Serializable {


     private Integer gradeId;
     private String gradeName;
     private Set<SubjectResult> subjectResults = new HashSet<SubjectResult>(0);
     private Set<SemisterResult> semisterResults = new HashSet<SemisterResult>(0);
     private Set<FinalResult> finalResults = new HashSet<FinalResult>(0);

    public Grade() {
    }

	
    public Grade(String gradeName) {
        this.gradeName = gradeName;
    }
    public Grade(String gradeName, Set<SubjectResult> subjectResults, Set<SemisterResult> semisterResults, Set<FinalResult> finalResults) {
       this.gradeName = gradeName;
       this.subjectResults = subjectResults;
       this.semisterResults = semisterResults;
       this.finalResults = finalResults;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="grade_id", unique=true, nullable=false)
    public Integer getGradeId() {
        return this.gradeId;
    }
    
    public void setGradeId(Integer gradeId) {
        this.gradeId = gradeId;
    }

    
    @Column(name="grade_name", nullable=false, length=45)
    public String getGradeName() {
        return this.gradeName;
    }
    
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grade")
    public Set<SubjectResult> getSubjectResults() {
        return this.subjectResults;
    }
    
    public void setSubjectResults(Set<SubjectResult> subjectResults) {
        this.subjectResults = subjectResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grade")
    public Set<SemisterResult> getSemisterResults() {
        return this.semisterResults;
    }
    
    public void setSemisterResults(Set<SemisterResult> semisterResults) {
        this.semisterResults = semisterResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grade")
    public Set<FinalResult> getFinalResults() {
        return this.finalResults;
    }
    
    public void setFinalResults(Set<FinalResult> finalResults) {
        this.finalResults = finalResults;
    }




}


