package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="university"
)
public class Login  implements java.io.Serializable {


     private Integer loginId;
     private AccountType accountType;
     private StudentInfo studentInfo;
     private Teachers teachers;
     private String uname;
     private String pass;

    public Login() {
    }

	
    public Login(AccountType accountType, String uname, String pass) {
        this.accountType = accountType;
        this.uname = uname;
        this.pass = pass;
    }
    public Login(AccountType accountType, StudentInfo studentInfo, Teachers teachers, String uname, String pass) {
       this.accountType = accountType;
       this.studentInfo = studentInfo;
       this.teachers = teachers;
       this.uname = uname;
       this.pass = pass;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="login_id", unique=true, nullable=false)
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="acc_type_id", nullable=false)
    public AccountType getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_id")
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id")
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }

    
    @Column(name="uname", nullable=false, length=45)
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    
    @Column(name="pass", nullable=false, length=45)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


