package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NoticeCategory generated by hbm2java
 */
@Entity
@Table(name="notice_category"
    ,catalog="university"
    , uniqueConstraints = @UniqueConstraint(columnNames="ncat_name") 
)
public class NoticeCategory  implements java.io.Serializable {


     private Integer ncatId;
     private String ncatName;
     private Set<NoticeDetails> noticeDetailses = new HashSet<NoticeDetails>(0);

    public NoticeCategory() {
    }

	
    public NoticeCategory(String ncatName) {
        this.ncatName = ncatName;
    }
    public NoticeCategory(String ncatName, Set<NoticeDetails> noticeDetailses) {
       this.ncatName = ncatName;
       this.noticeDetailses = noticeDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ncat_id", unique=true, nullable=false)
    public Integer getNcatId() {
        return this.ncatId;
    }
    
    public void setNcatId(Integer ncatId) {
        this.ncatId = ncatId;
    }

    
    @Column(name="ncat_name", unique=true, nullable=false, length=45)
    public String getNcatName() {
        return this.ncatName;
    }
    
    public void setNcatName(String ncatName) {
        this.ncatName = ncatName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="noticeCategory")
    public Set<NoticeDetails> getNoticeDetailses() {
        return this.noticeDetailses;
    }
    
    public void setNoticeDetailses(Set<NoticeDetails> noticeDetailses) {
        this.noticeDetailses = noticeDetailses;
    }




}


