package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Routine generated by hbm2java
 */
@Entity
@Table(name="routine"
    ,catalog="university"
)
public class Routine  implements java.io.Serializable {


     private Integer routineId;
     private ClassDay classDay;
     private ClassHour classHour;
     private Subject subject;
     private Teachers teachers;

    public Routine() {
    }

    public Routine(ClassDay classDay, ClassHour classHour, Subject subject, Teachers teachers) {
       this.classDay = classDay;
       this.classHour = classHour;
       this.subject = subject;
       this.teachers = teachers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="routine_id", unique=true, nullable=false)
    public Integer getRoutineId() {
        return this.routineId;
    }
    
    public void setRoutineId(Integer routineId) {
        this.routineId = routineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="day_id", nullable=false)
    public ClassDay getClassDay() {
        return this.classDay;
    }
    
    public void setClassDay(ClassDay classDay) {
        this.classDay = classDay;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hour_id", nullable=false)
    public ClassHour getClassHour() {
        return this.classHour;
    }
    
    public void setClassHour(ClassHour classHour) {
        this.classHour = classHour;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="teacher_id", nullable=false)
    public Teachers getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Teachers teachers) {
        this.teachers = teachers;
    }




}


