package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Semister generated by hbm2java
 */
@Entity
@Table(name="semister"
    ,catalog="university"
)
public class Semister  implements java.io.Serializable {


     private Integer semId;
     private String semName;
     private Set<SemisterResult> semisterResults = new HashSet<SemisterResult>(0);
     private Set<Exam> exams = new HashSet<Exam>(0);
     private Set<Subject> subjects = new HashSet<Subject>(0);
     private Set<StudentAssigne> studentAssignes = new HashSet<StudentAssigne>(0);

    public Semister() {
    }

	
    public Semister(String semName) {
        this.semName = semName;
    }
    public Semister(String semName, Set<SemisterResult> semisterResults, Set<Exam> exams, Set<Subject> subjects, Set<StudentAssigne> studentAssignes) {
       this.semName = semName;
       this.semisterResults = semisterResults;
       this.exams = exams;
       this.subjects = subjects;
       this.studentAssignes = studentAssignes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sem_id", unique=true, nullable=false)
    public Integer getSemId() {
        return this.semId;
    }
    
    public void setSemId(Integer semId) {
        this.semId = semId;
    }

    
    @Column(name="sem_name", nullable=false, length=45)
    public String getSemName() {
        return this.semName;
    }
    
    public void setSemName(String semName) {
        this.semName = semName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semister")
    public Set<SemisterResult> getSemisterResults() {
        return this.semisterResults;
    }
    
    public void setSemisterResults(Set<SemisterResult> semisterResults) {
        this.semisterResults = semisterResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semister")
    public Set<Exam> getExams() {
        return this.exams;
    }
    
    public void setExams(Set<Exam> exams) {
        this.exams = exams;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semister")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="semister")
    public Set<StudentAssigne> getStudentAssignes() {
        return this.studentAssignes;
    }
    
    public void setStudentAssignes(Set<StudentAssigne> studentAssignes) {
        this.studentAssignes = studentAssignes;
    }




}


