package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SemisterResult generated by hbm2java
 */
@Entity
@Table(name="semister_result"
    ,catalog="university"
)
public class SemisterResult  implements java.io.Serializable {


     private Integer semResultId;
     private Department department;
     private Grade grade;
     private Program program;
     private Semister semister;
     private StudentInfo studentInfo;
     private double gpa;

    public SemisterResult() {
    }

    public SemisterResult(Department department, Grade grade, Program program, Semister semister, StudentInfo studentInfo, double gpa) {
       this.department = department;
       this.grade = grade;
       this.program = program;
       this.semister = semister;
       this.studentInfo = studentInfo;
       this.gpa = gpa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sem_result_id", unique=true, nullable=false)
    public Integer getSemResultId() {
        return this.semResultId;
    }
    
    public void setSemResultId(Integer semResultId) {
        this.semResultId = semResultId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grade_id", nullable=false)
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sem_id", nullable=false)
    public Semister getSemister() {
        return this.semister;
    }
    
    public void setSemister(Semister semister) {
        this.semister = semister;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

    
    @Column(name="gpa", nullable=false, precision=22, scale=0)
    public double getGpa() {
        return this.gpa;
    }
    
    public void setGpa(double gpa) {
        this.gpa = gpa;
    }




}


