package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * StudentInfo generated by hbm2java
 */
@Entity
@Table(name="student_info"
    ,catalog="university"
    , uniqueConstraints = {@UniqueConstraint(columnNames="st_reg"), @UniqueConstraint(columnNames="st_roll")} 
)
public class StudentInfo  implements java.io.Serializable {


     private Integer stId;
     private String stName;
     private String stFather;
     private String stMother;
     private String stAddress;
     private String stMobile;
     private String stEmail;
     private Date stDob;
     private String stPic;
     private String stSession;
     private int stRoll;
     private int stReg;
     private Date admissionDate;
     private Set<Attendence> attendences = new HashSet<Attendence>(0);
     private Set<SemisterResult> semisterResults = new HashSet<SemisterResult>(0);
     private Set<StudentAssigne> studentAssignes = new HashSet<StudentAssigne>(0);
     private Set<FinalResult> finalResults = new HashSet<FinalResult>(0);
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<SubjectResult> subjectResults = new HashSet<SubjectResult>(0);
     private Set<StudentFee> studentFees = new HashSet<StudentFee>(0);

    public StudentInfo() {
    }

	
    public StudentInfo(String stName, String stFather, String stMother, String stAddress, String stMobile, String stEmail, Date stDob, String stPic, String stSession, int stRoll, int stReg, Date admissionDate) {
        this.stName = stName;
        this.stFather = stFather;
        this.stMother = stMother;
        this.stAddress = stAddress;
        this.stMobile = stMobile;
        this.stEmail = stEmail;
        this.stDob = stDob;
        this.stPic = stPic;
        this.stSession = stSession;
        this.stRoll = stRoll;
        this.stReg = stReg;
        this.admissionDate = admissionDate;
    }
    public StudentInfo(String stName, String stFather, String stMother, String stAddress, String stMobile, String stEmail, Date stDob, String stPic, String stSession, int stRoll, int stReg, Date admissionDate, Set<Attendence> attendences, Set<SemisterResult> semisterResults, Set<StudentAssigne> studentAssignes, Set<FinalResult> finalResults, Set<Login> logins, Set<SubjectResult> subjectResults, Set<StudentFee> studentFees) {
       this.stName = stName;
       this.stFather = stFather;
       this.stMother = stMother;
       this.stAddress = stAddress;
       this.stMobile = stMobile;
       this.stEmail = stEmail;
       this.stDob = stDob;
       this.stPic = stPic;
       this.stSession = stSession;
       this.stRoll = stRoll;
       this.stReg = stReg;
       this.admissionDate = admissionDate;
       this.attendences = attendences;
       this.semisterResults = semisterResults;
       this.studentAssignes = studentAssignes;
       this.finalResults = finalResults;
       this.logins = logins;
       this.subjectResults = subjectResults;
       this.studentFees = studentFees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="st_id", unique=true, nullable=false)
    public Integer getStId() {
        return this.stId;
    }
    
    public void setStId(Integer stId) {
        this.stId = stId;
    }

    
    @Column(name="st_name", nullable=false, length=45)
    public String getStName() {
        return this.stName;
    }
    
    public void setStName(String stName) {
        this.stName = stName;
    }

    
    @Column(name="st_father", nullable=false, length=45)
    public String getStFather() {
        return this.stFather;
    }
    
    public void setStFather(String stFather) {
        this.stFather = stFather;
    }

    
    @Column(name="st_mother", nullable=false, length=45)
    public String getStMother() {
        return this.stMother;
    }
    
    public void setStMother(String stMother) {
        this.stMother = stMother;
    }

    
    @Column(name="st_address", nullable=false, length=45)
    public String getStAddress() {
        return this.stAddress;
    }
    
    public void setStAddress(String stAddress) {
        this.stAddress = stAddress;
    }

    
    @Column(name="st_mobile", nullable=false, length=45)
    public String getStMobile() {
        return this.stMobile;
    }
    
    public void setStMobile(String stMobile) {
        this.stMobile = stMobile;
    }

    
    @Column(name="st_email", nullable=false, length=45)
    public String getStEmail() {
        return this.stEmail;
    }
    
    public void setStEmail(String stEmail) {
        this.stEmail = stEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="st_dob", nullable=false, length=10)
    public Date getStDob() {
        return this.stDob;
    }
    
    public void setStDob(Date stDob) {
        this.stDob = stDob;
    }

    
    @Column(name="st_pic", nullable=false, length=5000)
    public String getStPic() {
        return this.stPic;
    }
    
    public void setStPic(String stPic) {
        this.stPic = stPic;
    }

    
    @Column(name="st_session", nullable=false, length=50)
    public String getStSession() {
        return this.stSession;
    }
    
    public void setStSession(String stSession) {
        this.stSession = stSession;
    }

    
    @Column(name="st_roll", unique=true, nullable=false)
    public int getStRoll() {
        return this.stRoll;
    }
    
    public void setStRoll(int stRoll) {
        this.stRoll = stRoll;
    }

    
    @Column(name="st_reg", unique=true, nullable=false)
    public int getStReg() {
        return this.stReg;
    }
    
    public void setStReg(int stReg) {
        this.stReg = stReg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="admission_date", nullable=false, length=10)
    public Date getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set<Attendence> attendences) {
        this.attendences = attendences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<SemisterResult> getSemisterResults() {
        return this.semisterResults;
    }
    
    public void setSemisterResults(Set<SemisterResult> semisterResults) {
        this.semisterResults = semisterResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<StudentAssigne> getStudentAssignes() {
        return this.studentAssignes;
    }
    
    public void setStudentAssignes(Set<StudentAssigne> studentAssignes) {
        this.studentAssignes = studentAssignes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<FinalResult> getFinalResults() {
        return this.finalResults;
    }
    
    public void setFinalResults(Set<FinalResult> finalResults) {
        this.finalResults = finalResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<SubjectResult> getSubjectResults() {
        return this.subjectResults;
    }
    
    public void setSubjectResults(Set<SubjectResult> subjectResults) {
        this.subjectResults = subjectResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="studentInfo")
    public Set<StudentFee> getStudentFees() {
        return this.studentFees;
    }
    
    public void setStudentFees(Set<StudentFee> studentFees) {
        this.studentFees = studentFees;
    }




}


