package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentAssigne generated by hbm2java
 */
@Entity
@Table(name="student_assigne"
    ,catalog="university"
)
public class StudentAssigne  implements java.io.Serializable {


     private Integer assigneId;
     private Department department;
     private Program program;
     private Semister semister;
     private StudentInfo studentInfo;
     private Subject subject;

    public StudentAssigne() {
    }

    public StudentAssigne(Department department, Program program, Semister semister, StudentInfo studentInfo, Subject subject) {
       this.department = department;
       this.program = program;
       this.semister = semister;
       this.studentInfo = studentInfo;
       this.subject = subject;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="assigne_id", unique=true, nullable=false)
    public Integer getAssigneId() {
        return this.assigneId;
    }
    
    public void setAssigneId(Integer assigneId) {
        this.assigneId = assigneId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sem_id", nullable=false)
    public Semister getSemister() {
        return this.semister;
    }
    
    public void setSemister(Semister semister) {
        this.semister = semister;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }




}


