package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SubjectResult generated by hbm2java
 */
@Entity
@Table(name="subject_result"
    ,catalog="university"
)
public class SubjectResult  implements java.io.Serializable {


     private Integer subResultId;
     private Grade grade;
     private StudentInfo studentInfo;
     private Subject subject;
     private int marks;
     private int markObtaine;
     private double gpa;

    public SubjectResult() {
    }

    public SubjectResult(Grade grade, StudentInfo studentInfo, Subject subject, int marks, int markObtaine, double gpa) {
       this.grade = grade;
       this.studentInfo = studentInfo;
       this.subject = subject;
       this.marks = marks;
       this.markObtaine = markObtaine;
       this.gpa = gpa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_result_id", unique=true, nullable=false)
    public Integer getSubResultId() {
        return this.subResultId;
    }
    
    public void setSubResultId(Integer subResultId) {
        this.subResultId = subResultId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grade_id", nullable=false)
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="st_id", nullable=false)
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sub_id", nullable=false)
    public Subject getSubject() {
        return this.subject;
    }
    
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    
    @Column(name="marks", nullable=false)
    public int getMarks() {
        return this.marks;
    }
    
    public void setMarks(int marks) {
        this.marks = marks;
    }

    
    @Column(name="mark_obtaine", nullable=false)
    public int getMarkObtaine() {
        return this.markObtaine;
    }
    
    public void setMarkObtaine(int markObtaine) {
        this.markObtaine = markObtaine;
    }

    
    @Column(name="gpa", nullable=false, precision=22, scale=0)
    public double getGpa() {
        return this.gpa;
    }
    
    public void setGpa(double gpa) {
        this.gpa = gpa;
    }




}


