package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name="subject"
    ,catalog="university"
)
public class Subject  implements java.io.Serializable {


     private Integer subId;
     private Department department;
     private Program program;
     private Semister semister;
     private String subName;
     private Set<ExamSchedule> examSchedules = new HashSet<ExamSchedule>(0);
     private Set<SubjectResult> subjectResults = new HashSet<SubjectResult>(0);
     private Set<StudentAssigne> studentAssignes = new HashSet<StudentAssigne>(0);
     private Set<Attendence> attendences = new HashSet<Attendence>(0);
     private Set<Routine> routines = new HashSet<Routine>(0);

    public Subject() {
    }

	
    public Subject(Department department, Program program, Semister semister, String subName) {
        this.department = department;
        this.program = program;
        this.semister = semister;
        this.subName = subName;
    }
    public Subject(Department department, Program program, Semister semister, String subName, Set<ExamSchedule> examSchedules, Set<SubjectResult> subjectResults, Set<StudentAssigne> studentAssignes, Set<Attendence> attendences, Set<Routine> routines) {
       this.department = department;
       this.program = program;
       this.semister = semister;
       this.subName = subName;
       this.examSchedules = examSchedules;
       this.subjectResults = subjectResults;
       this.studentAssignes = studentAssignes;
       this.attendences = attendences;
       this.routines = routines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_id", unique=true, nullable=false)
    public Integer getSubId() {
        return this.subId;
    }
    
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sem_id", nullable=false)
    public Semister getSemister() {
        return this.semister;
    }
    
    public void setSemister(Semister semister) {
        this.semister = semister;
    }

    
    @Column(name="sub_name", nullable=false, length=45)
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<ExamSchedule> getExamSchedules() {
        return this.examSchedules;
    }
    
    public void setExamSchedules(Set<ExamSchedule> examSchedules) {
        this.examSchedules = examSchedules;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<SubjectResult> getSubjectResults() {
        return this.subjectResults;
    }
    
    public void setSubjectResults(Set<SubjectResult> subjectResults) {
        this.subjectResults = subjectResults;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<StudentAssigne> getStudentAssignes() {
        return this.studentAssignes;
    }
    
    public void setStudentAssignes(Set<StudentAssigne> studentAssignes) {
        this.studentAssignes = studentAssignes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set<Attendence> attendences) {
        this.attendences = attendences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subject")
    public Set<Routine> getRoutines() {
        return this.routines;
    }
    
    public void setRoutines(Set<Routine> routines) {
        this.routines = routines;
    }




}


