package com.mostafa.university.domain;
// Generated Aug 2, 2018 10:23:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teachers generated by hbm2java
 */
@Entity
@Table(name="teachers"
    ,catalog="university"
)
public class Teachers  implements java.io.Serializable {


     private Integer teacherId;
     private Department department;
     private EmpInfo empInfo;
     private Set<Login> logins = new HashSet<Login>(0);
     private Set<Routine> routines = new HashSet<Routine>(0);
     private Set<Attendence> attendences = new HashSet<Attendence>(0);

    public Teachers() {
    }

	
    public Teachers(Department department, EmpInfo empInfo) {
        this.department = department;
        this.empInfo = empInfo;
    }
    public Teachers(Department department, EmpInfo empInfo, Set<Login> logins, Set<Routine> routines, Set<Attendence> attendences) {
       this.department = department;
       this.empInfo = empInfo;
       this.logins = logins;
       this.routines = routines;
       this.attendences = attendences;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="teacher_id", unique=true, nullable=false)
    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dep_id", nullable=false)
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_id", nullable=false)
    public EmpInfo getEmpInfo() {
        return this.empInfo;
    }
    
    public void setEmpInfo(EmpInfo empInfo) {
        this.empInfo = empInfo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teachers")
    public Set<Login> getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teachers")
    public Set<Routine> getRoutines() {
        return this.routines;
    }
    
    public void setRoutines(Set<Routine> routines) {
        this.routines = routines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teachers")
    public Set<Attendence> getAttendences() {
        return this.attendences;
    }
    
    public void setAttendences(Set<Attendence> attendences) {
        this.attendences = attendences;
    }




}


